# (Re)set the values for cf.apiHost, cf.username, and cf.password
# or set these as environment variables or command-line arguments. E.g.,
#
# as Environment variables
#
# CF_API_HOST=api.run.pivotal.io
# CF_USERNAME=me@host.io
# CF_PASSWORD=xXxXxX
#
# as Command-line arguments
#
# -Dcf.apiHost=api.run.pivotal.io
# -Dcf.username=me@host.io
# -Dcf.password=xXxXxX
#
cf:
  apiHost: api.run.pivotal.io
  username: replace_me
  password: replace_me


# Uncomment and (re)set the values for spring.mail.username, spring.mail.password
# mail.from, and mail.recipients
# Configuration below is set up to work w/ a Gmail account
# @see http://www.baeldung.com/spring-email
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: replace_me
    password: replace_me
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # SendGrid API key (alternative to username/password).
  sendgrid:
    api-key: replace_me

mail:
  from: replace_me
  recipients: 
#  - recipient_account
  subject: "PCF Application Inventory Report"

logging:
  level:
    de.flapdoodle.embed.mongo: INFO
    org.springframework: INFO
    com.sendgrid: DEBUG

# Options are: none, java-mail or sendgrid
notification:
  engine: none

# Set schedule for this task to adhere to
# @see https://crontab.guru for help, first parameter is seconds
cron: "0 * * * * *"

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,scheduledtasks,loggers

---
spring:
  profiles: mongo

  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  mongodb:
    embedded:
      version: 3.4.15
      download:
        path: https://fastdl.mongodb.org/
        alternate: true

---
spring:
  profiles: jdbc

  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
    - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
    - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
    - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
    - org.springframework.boot.autoconfigure.data.mongo.MongoReactiveDataAutoConfiguration

  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:cf-application-inventory
    username: sa
    password: 

---
## Assumes naming convention for secrets service
## Name of credhub service instance must be cf-app-inventory-report-secrets
spring:
  profiles: secrets
  profiles.include: 
  - jdbc

  credhub:
    url: https://credhub.service.cf.internal:8844

  mail:
    host: ${vcap.services.cf-app-inventory-report-secrets.credentials.MAIL_HOST:}
    port: ${vcap.services.cf-app-inventory-report-secrets.credentials.MAIL_PORT:}
    username: ${vcap.services.cf-app-inventory-report-secrets.credentials.MAIL_USERNAME:}
    password: ${vcap.services.cf-app-inventory-report-secrets.credentials.MAIL_PASSWORD:}

  sendgrid:
    api-key: ${vcap.services.cf-app-inventory-report-secrets.credentials.SENDGRID_API-KEY:}

cf:
  apiHost: ${vcap.services.cf-app-inventory-report-secrets.credentials.CF_API-HOST:api.run.pcfone.io}
  username: ${vcap.services.cf-app-inventory-report-secrets.credentials.CF_USERNAME}
  password: ${vcap.services.cf-app-inventory-report-secrets.credentials.CF_PASSWORD}

mail:
  from: ${vcap.services.cf-app-inventory-report-secrets.credentials.MAIL_FROM:admin@pcfone.io}
  recipients: ${vcap.services.cf-app-inventory-report-secrets.credentials.MAIL_RECIPIENTS:}

cron: ${vcap.services.cf-app-inventory-report-secrets.credentials.CRON:0 0 8 * * 1}

notification:
  engine: ${vcap.services.cf-app-inventory-report-secrets.credentials.NOTIFICATION_ENGINE:none}
