# Uncomment and (re)set the values for cf.apiHost, cf.username, and cf.password
# or set these as environment variables or command-line arguments. E.g.,
#
# as Environment variables
#
# CF_API_HOST=api.run.pivotal.io
# CF_USERNAME=me@host.io
# CF_PASSWORD=xXxXxX
#
# as Command-line arguments
#
# -Dcf.apiHost=api.run.pivotal.io
# -Dcf.username=me@host.io
# -Dcf.password=xXxXxX
#
cf:
  apiHost: api.run.pivotal.io
#  username: your_username
#  password: your_password


# Uncomment and (re)set the values for spring.mail.username, spring.mail.password
# and spring.mail.recipients
# Configuration below is set up to work w/ a Gmail account
# @see http://www.baeldung.com/spring-email
spring:
  mail:
    host: smtp.gmail.com
    port: 587
#    username: your_gmail_account
#    password: your_gmail_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#    recipients: 
#      - recipient_account
    subject: "PCF Application Inventory Report"
