cf:
  apiHost: api.run.pcfone.io
  refreshToken: xxxxxx

token:
  provider: sso

spring:
  profiles.include: jdbc

logging:
  level:
    de.flapdoodle.embed.mongo: INFO
    org.springframework: INFO
    com.sendgrid: DEBUG
    org.cloudfoundry.reactor: DEBUG

# Options are: none, java-mail or sendgrid
notification:
  engine: none

# Set schedule for this task to adhere to
# @see https://crontab.guru for help, first parameter is seconds
cron: "0 0 8 * * 1"

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,scheduledtasks,loggers,logfile

---
spring:
  profiles: mongo

  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  mongodb:
    embedded:
      version: 3.4.15
      download:
        path: https://fastdl.mongodb.org/
        alternate: true

---
spring:
  profiles: jdbc

  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
    - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
    - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
    - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
    - org.springframework.boot.autoconfigure.data.mongo.MongoReactiveDataAutoConfiguration

  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:cf-application-inventory
    username: sa
    password: 
